
const Houses = {
    "Adult Great Fairy's Fountain": "Adult Great Fairy's Fountain",
    "Back Alley House": "Back Alley House",
    "Bazaar": "Bazaar",
    "Bombchu Bowling": "Bombchu Bowling",
    "Bombchu Shop": "Bombchu Shop",
    "Bosses Hut": "Bosses Hut",
    "Bottom House": "Bottom House",
    "Child Great Fairy's Fountain": "Child Great Fairy's Fountain",
    "Dampe's Hut": "Dampe's Hut",
    "Fairy Fountain": "Fairy Fountain",
    "Fishing": "Fishing",
    "Granny's Potion Shop": "Granny's Potion Shop",
    "Great Fairy's Fountain": "Great Fairy's Fountain",
    "Guard Hut/Poe Collector": "Guard Hut/Poe Collector",
    "House": "House",
    "Impa's House Cow": "Impa's House Cow",
    "Impa's House Front": "Impa's House Front",
    "Know-It-All House": "Know-It-All House",
    "Lake Hylia Lab": "Lake Hylia Lab",
    "Link's House": "Link's House",
    "Lon Lon Tower": "Lon Lon Tower",
    "Mask Shop": "Mask Shop",
    "Mido's House": "Mido's House",
    "Potion Shop": "Potion Shop",
    "Saria's House": "Saria's House",
    "Shooting Gallery": "Shooting Gallery",
    "Shop": "Shop",
    "Skulltula House": "Skulltula House",
    "Stable": "Stable",
    "Talon's House": "Talon's House",
    "Temple of Time": "Temple of Time",
    "Treasure Chest Game": "Treasure Chest Game",
    "Twins House": "Twins House",
    "Windmill": "Windmill"
};

export default Houses;
