
const Houses = {
    "AdultGreatFairy": "Adult Great Fairy's Fountain",
    "BackAlleyHouse": "Back Alley House",
    "Bazaar": "Bazaar",
    "BombchuBowling": "Bombchu Bowling",
    "BombchuShop": "Bombchu Shop",
    "BossesHut": "Bosses Hut",
    "BottomHouse": "Bottom House",
    "ChildGreatFairy": "Child Great Fairy's Fountain",
    "DampesHut": "Dampe's Hut",
    "FairyFountain": "Fairy Fountain",
    "Fishing": "Fishing",
    "GrannysPotionShop": "Granny's Potion Shop",
    "GreatFairyFountain": "Great Fairy's Fountain",
    "GuardHutPoeShop": "Guard Hut/Poe Shop",
    "House": "House",
    "ImpasHouseCow": "Impa's House Cow",
    "ImpasHouseFront": "Impa's House Front",
    "KnowItAllHouse": "Know-It-All House",
    "LinksHouse": "Link's House",
    "MaskShop": "Mask Shop",
    "MidosHouse": "Mido's House",
    "PotionShop": "Potion Shop",
    "SariasHouse": "Saria's House",
    "ShootingGallery": "Shooting Gallery",
    "Shop": "Shop",
    "SkulltulaHouse": "Skulltula House",
    "Stables": "Stables",
    "TalonsHouse": "Talon's House",
    "TempleOfTime": "Temple of Time",
    "TreasureChestGame": "Treasure Chest Game",
    "LonLonTower": "Lon Lon Tower",
    "TwinsHouse": "Twins House",
    "LakeHyliaLab": "Lake Hylia Lab",
    "Windmill": "Windmill"
};

export default Houses;
